### ISSUE TITLE
Upload time is affected by buffer reallocations

### ISSUE THREAD

**Issue by bitblitz** [soterinsights/speedtest#4]
See line 103/114 here.  The continual reallocation of buffers swamps the performance if the buffer is large enough (10s of MB).

https://github.com/bitblitz/speedtest/commit/5ffb37e50156498ebabe6ee0525f24eba794e922

**Comment by snoj** [comment]
Thanks @bitblitz! I'll try to find some time this weekend to get this into the master branch.

**Comment by pedro-nonfree** [comment]
I see that this is still not in the master branch. Any news? Cheers

**Comment by snoj** [comment]
Basically...didn't have time and forgot about it.

**Comment by snoj** [comment]
done f7bba5ee30d1b0f7ea325272e3be7ec889b99e81
