### ISSUE TITLE
Results show "MB" when it should be "Mb"

### ISSUE THREAD

**Issue by bcacbe** [soterinsights/speedtest#5]
Hello, the results show "MB" (Megabyte) when it should show "Mb" (Megabit).

For example I have a 100"Mbps"/10"Mbps" Internet connection and when i run a test it shows 100"MB" download and 10"MB" upload, the problem is 100"MB" is 800 Mbps, which is wrong. 

Essiantly that capital "B" in MB needs to be lowercase.

Can you tell me under which file I can make an adjustment?

**Comment by mudpuddle** [comment]
those strings are located in html/speed.js.  A quick search should turn them up.

**Comment by snoj** [comment]
fixed 3b2f097cf29938cb7ee4b35405216f081caa318a
