### ISSUE TITLE
Speed rate limited to about 250Mbps

### ISSUE THREAD

**Issue by apwelsh** [soterinsights/speedtest#7]
Testing on localhost, and on Gigabit connected direct link, the max speed test result is 250Mbps

**Comment by snoj** [comment]
This is referenced in the readme.md. A quick test on my ubuntu laptop with master shows upper 700 and low 800Mbps for localhost only tests. Are you using Windows because I developed this on a Windows laptop and that's where the stats came from so long ago.

I'll see what can be done though.

**Comment by apwelsh** [comment]
hmm… I missed it.  Sorry about that.  On localhost, on windows, I do only get the 250Mbps max, but on linux, over shared gigabit connection, I get 480Mbps which is respectable.    Part of my issue with the linux host was my initial tests which were also slow were accidentally going through a proxy.  I bypassed it to get the faster speeds against linux.

Sorry to rehash an already acknowledged issue.    My take is it’s a Node.js performance issue for the slower windows numbers.

**Comment by snoj** [comment]
No worries. Easily missed. I'm just glad this tool is getting some use!

**Comment by snoj** [comment]
Okay, update.

You can edit the settings in the bin\config.json file. Increasing the max download and upload sizes as well as time lets the test run larger and longer which can get up to the Gbps range on localhost.

I've also updated the code if you want to take a look.

**Comment by apwelsh** [comment]
That’s awesome.  I’ll give it a shot.  I was thinking the same thing. 

Armand
--Sent from iPhone

**Comment by apwelsh** [comment]
The new update works great.  Without any tweaking I can now achieve nearly 1Gbps on a shared gigabit link.
