### ISSUE TITLE
Minimum node version required now is v4.5

### ISSUE THREAD

**Issue by drumadrian** [soterinsights/speedtest#8]
Hi, the recent updates broke when running on Node.js v4.4.5

I updated to Node.js v4.5 and the project is working again.  

References: 
https://github.com/lovell/sharp/issues/847
https://github.com/creationix/nvm/issues/437

Steps for the fix: 

nvm ls
nvm uninstall 4.4.5
nvm install 4.5
nvm alias default 4.5
nvm ls

**Comment by apwelsh** [comment]
I am on node 3.10.10 and it works fine for me.  Curious that it would work on the 3.x LTS version but inly on newer cersion of the 4.x branch.

**Comment by drumadrian** [comment]
I was using Amazon Linux on AWS.  It's derived from CentOS/RHEL -Red Hat Enterprise Linux.    I would have gathered more debugging information but I wasn't sure what could help.  I'm not a Javascript developer.  I hope this Issue helps others who run into the same issue.

**Comment by snoj** [comment]
Updated the package.json so minimum is v4.5 now. 8629f431e63c9d0bb21ca3345acb60cd57a975d1
