### ISSUE TITLE
Can't get working with PM2

### ISSUE THREAD

**Issue by d4rk22** [soterinsights/speedtest#9]
I love this program however I can't get it working with PM2. The current working directory seems to be wrong when launching with PM2 so I get the "404: file not found or more likely, you're trying to go somewhere you can't." like as if you were running just ./speed.js. Any tips for getting this to work with PM2?

**Comment by snoj** [comment]
This works for me.

```bash
git clone https://github.com/soterinsights/speedtest.git
cd speedtest
pm2 start ./bin/speed.js
```

If attempting to start while the working directory is bin, I get the same error you describe.

The reason for this is that speedtest/bin/speed.js assumes that pwd is speedtest, not speedtest/bin. So if the pwd is speedtest/bin, then it is looking for speedtest/bin/html for the static assets.

**Comment by d4rk22** [comment]
I can't remember what I was doing so I'm not sure what was wrong but this works just fine for me. Thanks for the help! I absolutely love this tool. So simple but I use it all the time to test the connectivity between my home internet and various routes.

**Comment by snoj** [comment]
Awesome! I'm glad it works now.

>So simple but I use it all the time to test the connectivity between my home internet and various routes.

That why it isn't on npm. It's suppose to be something you can grab the node exe and the speedtest-master zip from here, stuff them on a thumb drive and launch it on a client's server or workstation to test routes like vpns or private t1/fiber links.

**Comment by snoj** [comment]
Added a pm2 config json file for you as well as a root dir start script.

https://github.com/soterinsights/speedtest/commit/cf462abe9761c2459b6d6620c51e5bd65cb56264
